#!/bin/bash

# --- Audouin Setup Wizard ---
# This script generates all necessary config files and secrets.

# --- Colors ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Project Paths ---
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ENV_FILE="$PROJECT_DIR/.env"
GRAFANA_INI_PATH="$PROJECT_DIR/configs/grafana.ini"
PROM_YML_PATH="$PROJECT_DIR/prometheus/prometheus.yml"

# --- Function to check for root ---
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Error: This script must be run with sudo.${NC}"
        echo "Please run: sudo bash $0"
        exit 1
    fi
}

# --- Function to create directories ---
create_dirs() {
    echo -e "${YELLOW}Creating necessary directories...${NC}"
    mkdir -p "$PROJECT_DIR/prometheus"
    mkdir -p "$PROJECT_DIR/volumes/prometheus"
    mkdir -p "$PROJECT_DIR/volumes/grafana"
    mkdir -p "$PROJECT_DIR/provisioning/alerting"
    mkdir -p "$PROJECT_DIR/provisioning/dashboards"
    mkdir -p "$PROJECT_DIR/provisioning/datasources"
    mkdir -p "$PROJECT_DIR/configs"
    echo "Directories created."
}

# --- Function to gather secrets and configs ---
gather_configs() {
    echo -e "\n${GREEN}--- Audouin Configuration Wizard ---${NC}"
    
    # --- Grafana ---
    echo -e "\n${YELLOW}1. Grafana Setup${NC}"
    read -p "Enter Grafana admin password (default: changeme): " GRAFANA_ADMIN_PASS
    GRAFANA_ADMIN_PASS=${GRAFANA_ADMIN_PASS:-changeme}

    # --- SMTP ---
    echo -e "\n${YELLOW}2. Email Alert (SMTP) Setup${NC}"
    read -p "Enter SMTP host (e.g., smtp.gmail.com:587): " SMTP_HOST
    read -p "Enter SMTP user (e.g., your-email@gmail.com): " SMTP_USER
    read -sp "Enter SMTP password (e.g., Gmail App Password): " SMTP_PASS
    echo ""
    read -p "Enter 'From' Name (e.g., Audouin Alerter): " SMTP_FROM_NAME

    # --- Redis ---
    echo -e "\n${YELLOW}3. Redis Exporter Setup (for Master/Slaves)${NC}"
    read -p "Enter Redis username (default: gabriel): " REDIS_USER
    REDIS_USER=${REDIS_USER:-gabriel}
    read -sp "Enter '${REDIS_USER}' password: " GABRIEL_REDIS_PASS
    echo ""
    read -p "Enter Redis host:port (default: localhost:6379): " REDIS_HOST_PORT
    REDIS_HOST_PORT=${REDIS_HOST_PORT:-localhost:6379}

    # --- Sentinel ---
    echo -e "\n${YELLOW}4. Sentinel Exporter Setup${NC}"
    read -p "Enter Sentinel username (default: christopher): " SENTINEL_USER
    SENTINEL_USER=${SENTINEL_USER:-christopher}
    read -sp "Enter '${SENTINEL_USER}' password: " CHRISTOPHER_REDIS_PASS
    echo ""
    read -p "Enter Sentinel host:port (default: localhost:26379): " SENTINEL_HOST_PORT
    SENTINEL_HOST_PORT=${SENTINEL_HOST_PORT:-localhost:26379}

    # --- Prometheus Targets ---
    echo -e "\n${YELLOW}5. Prometheus Targets${NC}"
    echo "Enter all IPs/hosts for your exporters, separated by commas."
    echo "Example: localhost:9121, 10.8.1.3:9121, 10.8.1.4:9121"
    read -p "Redis targets (e.g., localhost:9121): " REDIS_TARGETS
    read -p "Sentinel targets (e.g., localhost:9355, 10.8.1.3:9355): " SENTINEL_TARGETS

    # --- Generate Files ---
    echo -e "\n${YELLOW}Generating config files...${NC}"
    
    # Generate .env file
    echo "Writing .env file..."
cat <<EOF > "$ENV_FILE"
# This file is auto-generated by setup.sh
# Do not commit this file to Git!

# --- Grafana ---
GRAFANA_ADMIN_PASS=${GRAFANA_ADMIN_PASS}

# --- SMTP ---
SMTP_PASS=${SMTP_PASS}

# --- Redis Exporter ---
REDIS_USER=${REDIS_USER}
GABRIEL_REDIS_PASS=${GABRIEL_REDIS_PASS}
REDIS_HOST_PORT=${REDIS_HOST_PORT}

# --- Sentinel Exporter ---
SENTINEL_USER=${SENTINEL_USER}
CHRISTOPHER_REDIS_PASS=${CHRISTOPHER_REDIS_PASS}
SENTINEL_HOST_PORT=${SENTINEL_HOST_PORT}
EOF
    chmod 600 "$ENV_FILE"

    # Generate configs/grafana.ini
    echo "Writing configs/grafana.ini..."
cat <<EOF > "$GRAFANA_INI_PATH"
[smtp]
enabled = true
host = ${SMTP_HOST}
user = ${SMTP_USER}
password = \${SMTP_PASS} ; This uses the variable from the .env file
from_address = ${SMTP_USER}
from_name = ${SMTP_FROM_NAME:-Audouin Alerter}
skip_verify = false

[alerting]
enabled = true
EOF

    # Generate prometheus/prometheus.yml
    echo "Writing prometheus/prometheus.yml..."
    # Convert comma-separated strings to YAML list format
    local prom_redis_targets=$(echo $REDIS_TARGETS | sed "s/,/\\', \\'/g" | sed "s/^/\\'/g" | sed "s/$/\\'/g")
    local prom_sentinel_targets=$(echo $SENTINEL_TARGETS | sed "s/,/\\', \\'/g" | sed "s/^/\\'/g" | sed "s/$/\\'/g")

cat <<EOF > "$PROM_YML_PATH"
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: [${prom_redis_targets}]

  - job_name: 'sentinel'
    static_configs:
      - targets: [${prom_sentinel_targets}]
EOF

    echo -e "${GREEN}Configuration files generated successfully.${NC}"
}

# --- Main execution ---
check_root

echo -e "${GREEN}Welcome to the Audouin setup wizard!${NC}"
echo "This script will create the necessary directories and generate all"
echo "config files based on your input."

create_dirs
gather_configs

echo -e "\n${GREEN}Setup complete!${NC}"
echo "You can now deploy the stack by running:"
echo -e "  ${YELLOW}sudo docker compose up -d${NC}"
